env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  no-mixed-spaces-and-tabs: 
    - 0
settings:
  react:
    version: latest
